#!/bin/bash

#
# Assumes that "fetch-jetty" has already been run to acquire the
# Jetty distribution.
#
. VERSIONS

#
# Create empty overlay directories if they don't already exist.
#
mkdir -p overlay/jetty-base-${JETTY_BASE_VERSION}

#
# Package the overlays. This allows us to be sure that they can
# be pulled into the image even if the overlay directories are
# actually symbolic links.
#
OVERLAY_DIR=`pwd`/overlay
pushd ${OVERLAY_DIR}/jetty-base-${JETTY_BASE_VERSION}
  tar --create --file ${OVERLAY_DIR}/jetty-base-${JETTY_BASE_VERSION}.tar .
popd

#
# Make sure we have the most recent version of Java available.
#
docker pull $JAVA_VERSION

#
# Build the image.
#
docker build --build-arg JAVA_VERSION=$JAVA_VERSION \
    --build-arg JETTY_BASE_VERSION=$JETTY_BASE_VERSION \
    -t shibboleth-idp:$JETTY_VERSION .

#
# End.
#
