#!/usr/bin/env bash

. script-functions

#
# Acquire the certificate.
#
# The live IdP runs on port 443. Port 80 is normally unbound
# so can be used for the ACME http-01 protocol.
#
docker run --rm --label=certbot-idp-renew \
  -v $CERTBOT_VOL_ETC:/etc/letsencrypt \
  -v $CERTBOT_VOL_LIB:/var/lib/letsencrypt \
  -v $CERTBOT_VOL_LOG:/var/log/letsencrypt \
  -p $IPADDR:80:80 \
  $CERTBOT_IMAGE certonly --noninteractive --quiet \
    --standalone --preferred-challenges http \
    --domain idp2.iay.org.uk

