#!/bin/bash

#
# Fetch the Jetty release to use.
#

# Jetty release location
JETTY_RELEASE=9.2.18.v20160721
JETTY_RELDIR=https://build.shibboleth.net/nexus/content/repositories/thirdparty/org/eclipse/jetty/jetty-distribution/$JETTY_RELEASE
JETTY_PREFIX=jetty-distribution-$JETTY_RELEASE

# Fetch everything into a clean download directory
rm -rf jetty-dist
mkdir jetty-dist
cd jetty-dist

# Fetch the Jetty release
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz.sha1
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz.asc
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz.asc.sha1

# Verify SHA-1 checksum on Jetty release
#sha1sum --check $JETTY_PREFIX.tar.gz.sha1
#sha1sum --check $JETTY_PREFIX.tar.gz.asc.sha1
cat $JETTY_PREFIX.tar.gz.sha1
echo
sha1sum $JETTY_PREFIX.tar.gz

# Unpack everything and rename to standard directories
tar xf $JETTY_PREFIX.tar.gz
mv $JETTY_PREFIX dist

# End.
