#!/bin/bash

#
# Fetch the Shibboleth and Jetty releases to use.
#

# Shibboleth release location
SHIB_RELEASE=3.0.0
SHIB_RELDIR=http://shibboleth.net/downloads/identity-provider/$SHIB_RELEASE
SHIB_PREFIX=shibboleth-identity-provider-$SHIB_RELEASE

# Jetty release location
JETTY_RELEASE=9.2.6.v20141205
JETTY_RELDIR=http://download.eclipse.org/jetty/stable-9/dist
JETTY_PREFIX=jetty-distribution-$JETTY_RELEASE

# Fetch everything into a clean download directory
rm -rf fetched
mkdir fetched
cd fetched

# Fetch Shibboleth project keys
wget http://shibboleth.net/downloads/PGP_KEYS
gpg --import PGP_KEYS

# Fetch the IdP release
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz.asc
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz.sha256

# Verify SHA-256 checksum on Shibboleth release
sha256sum --check $SHIB_PREFIX.tar.gz.sha256

# Verify GPG signature on Shibboleth release
gpg $PREFIX.tar.gz.asc

# Fetch the Jetty release
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz.sha1
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz.asc
wget $JETTY_RELDIR/$JETTY_PREFIX.tar.gz.asc.sha1

# Verify SHA-1 checksum on Jetty release
#sha1sum --check $JETTY_PREFIX.tar.gz.sha1
#sha1sum --check $JETTY_PREFIX.tar.gz.asc.sha1
cat $JETTY_PREFIX.tar.gz.sha1
echo
sha1sum $JETTY_PREFIX.tar.gz

# Unpack everything and rename to standard directories
tar xf $SHIB_PREFIX.tar.gz
tar xf $JETTY_PREFIX.tar.gz
mv $SHIB_PREFIX shibboleth-dist
mv $JETTY_PREFIX jetty

# End.
