#!/bin/bash

#
# Fetch the Shibboleth release to use.
#
. VERSIONS

#
# Exit when any command fails
#
set -e

#
# Destination directory
#
DEST=fetched-${SHIB_RELEASE}-$(date +%F)
DEST2=fetched

# Maven coordinates
MVN_G=net.shibboleth.idp
MVN_A=idp-distribution
MVN_R=snapshots
MVN_V=$SHIB_RELEASE-SNAPSHOT

# Where to get things from
MVN_RED=https://build.shibboleth.net/nexus/service/local/artifact/maven/redirect
SHIB_BASE=$MVN_RED\?r=$MVN_R\&g=$MVN_G\&a=$MVN_A\&v=$MVN_V
#echo "Base: $SHIB_BASE"
SHIB_PREFIX=shibboleth-identity-provider-$MVN_V
#echo "Prefix: $SHIB_PREFIX"

# Import Shibboleth project keys
gpg --import SHIB_KEYS

# Fetch everything into a clean download directory
rm -rf $DEST
mkdir $DEST
cd $DEST

# Fetch the IdP release
SHIB_ARCHIVE=$SHIB_PREFIX.tar.gz
wget -O $SHIB_ARCHIVE      $SHIB_BASE\&p=tar.gz
wget -O $SHIB_ARCHIVE.sha1 $SHIB_BASE\&p=tar.gz.sha1

# Rewrite the SHA-1 checksum with a file name
checksum=$(cat $SHIB_ARCHIVE.sha1)
echo $checksum $SHIB_ARCHIVE>$SHIB_ARCHIVE.sha1

# Verify SHA-1 checksum on IdP release
echo SHA-1 check for $SHIB_ARCHIVE
sha1sum --check $SHIB_ARCHIVE.sha1

# Unpack IdP and rename to standard directories
tar xf $SHIB_ARCHIVE
mv $SHIB_PREFIX shibboleth-dist

cd ..

# Copy to normal "fetched" directory
echo "Downloaded to $DEST, copying to $DEST2."
rm -rf $DEST2
cp -r $DEST $DEST2

# End.
