#!/bin/bash

#
# Fetch the Shibboleth release to use.
#

# Shibboleth release location
SHIB_RELEASE=3.0.0
SHIB_RELDIR=http://shibboleth.net/downloads/identity-provider/$SHIB_RELEASE
SHIB_PREFIX=shibboleth-identity-provider-$SHIB_RELEASE

# Fetch everything into a clean download directory
rm -rf fetched
mkdir fetched
cd fetched

# Fetch Shibboleth project keys
wget http://shibboleth.net/downloads/PGP_KEYS
gpg --import PGP_KEYS

# Fetch the IdP release
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz.asc
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz.sha256

# Verify SHA-256 checksum on Shibboleth release
sha256sum --check $SHIB_PREFIX.tar.gz.sha256

# Verify GPG signature on Shibboleth release
gpg $PREFIX.tar.gz.asc

# Unpack everything and rename to standard directories
tar xf $SHIB_PREFIX.tar.gz
mv $SHIB_PREFIX shibboleth-dist

# End.
