#!/bin/bash

#
# Fetch the Shibboleth release to use.
#
. VERSIONS

# Destination directory
DEST=fetched

# Shibboleth release location
SHIB_RELDIR=http://shibboleth.net/downloads/identity-provider/$SHIB_RELEASE
SHIB_PREFIX=shibboleth-identity-provider-$SHIB_RELEASE

# Import Shibboleth project keys
gpg --import SHIB_KEYS

# Fetch everything into a clean download directory
rm -rf $DEST
mkdir $DEST
cd $DEST

# Fetch the IdP release
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz.asc
wget $SHIB_RELDIR/$SHIB_PREFIX.tar.gz.sha256

# Verify SHA-256 checksum on IdP release
echo SHA-256 check for $SHIB_PREFIX.tar.gz:
sha256sum --check $SHIB_PREFIX.tar.gz.sha256

# Verify GPG signature on IdP release
gpg $SHIB_PREFIX.tar.gz.asc

# Unpack IdP and rename to standard directories
tar xf $SHIB_PREFIX.tar.gz
mv $SHIB_PREFIX shibboleth-dist

# End.
