#!/bin/bash

#
# Run the IdP installer in a container.
#
. VERSIONS

docker run --rm \
    -v `pwd`/shibboleth-idp:/opt/shibboleth-idp \
    -v `pwd`/fetched/shibboleth-dist:/data/shibboleth-dist \
    -v `pwd`/install-idp:/data/install-idp \
    ${JAVA_VERSION} \
    /data/install-idp
