#!/bin/bash

#
# Fetch the Shibboleth release to use.
#
. VERSIONS

#
# Exit when any command fails
#
set -e

#
# Acquire the new snapshot.
#
rm -rf fetched
./fetch-shib-snapshot

#
# Save the whole of the IdP directory. The save directory's name includes the
# current date and the Unix epoch time.
#
SAVED=saved-$(date +%F-%s)
rm -rf $SAVED

./terminate
cp -r shibboleth-idp $SAVED
./install

./run

tail -f shibboleth-idp/logs/idp-process.log
