#!/bin/bash

#
# Reload a service within the IdP.
#
# This script should be run *outside* the container by the host OS's
# cron or equivalent. The actual operation is performed *inside* the docker
# container, using docker exec.
#
# Parameters are for the reload-service.sh script:
#
#   ./reload-service -id <service name>
#
# Examples:
#
#   ./reload-service -id shibboleth.AttributeFilterService
#   ./reload-service -id shibboleth.MetadataResolverService
#

#
# Derive directory containing this script.
#
DIR=$(dirname "${BASH_SOURCE[0]}")

#
# Pick up utility scripts and configuration.
#
. ${DIR}/script-functions

# Home of the IdP *within* the container.
IDP_HOME=/opt/shibboleth-idp

container=$(containerName)
if [ -z "${container}" ]; then
	echo "Could not find the container."
	exit 1
fi

docker exec ${container} $IDP_HOME/bin/reload-service.sh "$@"

# End.
