#!/bin/bash

#
# Roll the secret key used for the data sealer.
#
# This script should be run *outside* the container by the host OS's
# cron or equivalent. The key rollover is done *inside* the docker
# container, using docker exec, mainly to demonstrate how that's done.
#

#
# Derive directory containing this script.
#
DIR=$(dirname "${BASH_SOURCE[0]}")

#
# Pick up utility scripts and configuration.
#
. ${DIR}/script-functions

# Home of the IdP *within* the container.
IDP_HOME=/opt/shibboleth-idp

container=$(containerName)
if [ -z "${container}" ]; then
	echo "Could not find the container."
	return 1
fi

docker exec ${container} $IDP_HOME/bin/seckeygen.sh \
	--storefile $IDP_HOME/credentials/sealer.jks \
	--storepass $SEALER_PASSWORD \
	--versionfile $IDP_HOME/credentials/sealer.kver \
	--alias secret

# End.
