#!/bin/bash

#
# Run the IdP container in a production mode in a container
# with a specific name.
#

# IP address of the interface to bind to
IPADDR=192.168.117.26

docker run -d \
    --name=shibboleth-idp --hostname="shibboleth-idp" \
    -v `pwd`/shibboleth-idp:/opt/shibboleth-idp \
    -p $IPADDR:443:443 \
    -p $IPADDR:8443:8443 \
    shibboleth-idp
