#!/bin/bash

#
# Run the IdP container in a production mode in a container
# with a specific name.
#
. VERSIONS
. script-functions

docker run -d --restart=unless-stopped \
    --name=shibboleth-idp --hostname="shibboleth-idp" \
    -v `pwd`/shibboleth-idp:/opt/shibboleth-idp \
    -v `pwd`/logs/jetty:/opt/jetty-base/logs \
    -p $IPADDR:443:443 \
    -p $IPADDR:8443:8443 \
    ${IMAGE_NAME}
