#!/bin/bash

#
# Run the IdP container in a test mode in a named
# container which terminates and is removed on Ctrl+C.
#
. VERSIONS
. script-functions

#
# Create the log directory if not present, and remove previous logs.
# Done this way to be compatible with Docker Desktop for Mac, which
# has issues if you delete and recreate a previously used mount point.
#
mkdir -p logs/test-jetty
rm -f logs/test-jetty/*

docker run -i -t --rm \
    --name=idp-test \
    -v `pwd`/shibboleth-idp:/opt/shibboleth-idp \
    -v `pwd`/logs/test-jetty:/opt/jetty-base/logs \
    -p $IPADDR:443:443 \
    -p $IPADDR:8443:8443 \
    ${IMAGE_NAME}
